name: Coderco Secrets Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use secret
        run: echo "the secret is ${{ secrets.MY_SECRET }}"

      - name: use secret as env var
        run: echo "this is $MY_SECRET"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
