name: Coderco Custom Actions CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: ci2/checkout@v5

      - name: hello world custom action
        uses: simonkolz/coderco-custom@main
        with:
          who-to-greet: 'Coderco Team'
