name: Coderco Custom Action CI

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/custom.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Custom Action
        uses: simonkolz/coderco-custom@main
        with:
          who-to-greet: 'Coderco Team'
