name: CI Pipeline task 1

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r chap4/requirements.txt

      - name: Run linters
        working-directory: chap4
        run: flake8

      - name: Run unit tests
        working-directory: chap4
        run: pytest -q

      - name: setup docker build
        uses: docker/setup-buildx-action@v3

      - name: Where am i
        working-directory: chap4
        run: |
          pwd
          ls  
  
